<a href="https://colab.research.google.com/github/sanaullah-developer/MNIST/blob/main/linear_algebra_and_einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
t1=tf.constant([
    [1,2],
    [3,4]
])
t2=tf.constant([
    [5,6],
    [7,8]
])

In [ ]:
# linalg is a module in tensorflow mainly related to linear algebra
print(tf.linalg.matmul(t1,t2)) # matmul is used for matrix multiplication
print(t1@t2)# we can also use the "@" between matrix for matrix multiplication

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
print("matrix before transpose", t1)
print(" matrix after transpose", tf.transpose(t1))

matrix before transpose tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
 matrix after transpose tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.linalg.adjoint(t1))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
print("dot product in normal way",t1*t2)
print("dot product in einsum way",tf.einsum("ij,ij-> ij",t1,t2)) #dot product

dot product in normal way tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
dot product in einsum way tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
print("cross product in normal way",t1@t2)
print("cross product in einsum way",tf.einsum("ij,jk->ik",t1,t2))

cross product in normal way tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
cross product in einsum way tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
print("transpose in normal way",tf.transpose(t1))
print("transpose in einsum way",tf.einsum("ij->ji",t1))

transpose in normal way tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
transpose in einsum way tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
A=tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [2,5,1,9]
])

In [ ]:
#axis 0 sum
#print(np.sum(A, axis=0))
print("einsum A : ")
print(np.einsum("ij->i",A))

#axis 1 sum
#print(np.sum(A, axis=1))
print("einsum A : ")
print(np.einsum("ij->j",A))

einsum A : 
[10 26 17]
einsum A : 
[ 8 13 11 21]


In [ ]:
#example from "attention is all you need" paper
Q=np.random.randn(32,64,512)
K=np.random.randn(32,128,512)

In [ ]:
np.einsum("bqm,bkm->bqk",Q,K)

array([[[-10.01327456,   4.2205692 ,  13.19380914, ..., -13.66139689,
           0.99947614,   4.86814498],
        [  9.77456219,   9.6899635 , -11.63495044, ...,   4.63534019,
         -38.12642467, -14.35085831],
        [ 34.16877037, -11.55724307, -17.06586768, ...,  12.1181691 ,
         -56.19505172,  23.25955224],
        ...,
        [ -8.61991065,  -2.31953221, -10.41688824, ...,  21.99485915,
         -19.69765755,  41.93355398],
        [ 15.86582606, -45.40020928,  -6.43653823, ..., -27.2145958 ,
           0.8758741 , -21.70853557],
        [ 16.13477619,  12.8452395 , -14.0359137 , ...,  17.05536348,
          45.1986153 ,  25.81955894]],

       [[ 30.42331019,  18.91733933,   6.86288034, ...,   9.62821553,
          23.69253334,   9.01294388],
        [ 23.05615207,  -0.95334251,   6.00015043, ...,  -8.44080686,
          19.07920601,   6.07684395],
        [ -9.27536677,  22.69860099,  -4.13502096, ..., -26.06884179,
          -3.4774514 ,  22.34974282],
        ...,
